### ISSUE TITLE
Problem with fit file created by Suunto watch

### ISSUE THREAD

**Issue by pronti** [MaksVasilev/fit2gpx#30]
When I try to convert my fit file I get following exception:
"C:\Program Files\jdk-16\bin\java.exe" -jar fit2gpx.jar  Mountaineering_2021-08-14T08_08_21.fit
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at Converter.fix(Converter.java:413)
        at Converter.run(Converter.java:194)
        at fit2gpx.main(fit2gpx.java:260)

[Mountaineering_2021-08-14T08_08_21.zip](https://github.com/MaksVasilev/fit2gpx/files/7037194/Mountaineering_2021-08-14T08_08_21.zip)

**Comment by MaksVasilev** [comment]
Fixed in last release https://github.com/MaksVasilev/fit2gpx/releases/tag/v0.1.18
